train_config:
  train_type: "ES"
  env_name: "MetaMaze-misc"
  num_generations: 5000
  evaluate_every_gen: 100

  env_name: "MetaMaze-misc"
  env_kwargs: {}
  env_params: {}
  num_test_rollouts: 164
  num_train_rollouts: 64

  es_name: "OpenES"
  es_config:
    popsize: 256
    opt_name: "adam"
  es_params:
    sigma_init: 0.1
    sigma_decay: 0.999
    sigma_limit: 0.001
  opt_params:
    lrate_init: 0.01
    lrate_decay: 0.999
    lrate_limit: 0.001

  fitness_config:
    maximize: true
    centered_rank: true
    z_score: false
    w_decay: 0.0

  network_name: "LSTM"
  network_config: 
    num_hidden_units: 48
    output_activation: "categorical"

log_config:
  time_to_track: ["num_steps"]
  what_to_track: ["return"]
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"

device_config:
  num_devices: 1
  device_type: "gpu"